# Generated by Django 4.2.20 on 2025-03-12 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockdiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('number', '数値'), ('text', 'テキスト'), ('select', '選択肢')], default='number', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choices', models.TextField(blank=True, help_text='選択肢項目の場合、カンマ区切りで選択肢を入力してください。')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis_template.analysistemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiaryAnalysisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('analysis_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_template.analysisitem')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_values', to='stockdiary.stockdiary')),
            ],
            options={
                'unique_together': {('diary', 'analysis_item')},
            },
        ),
    ]
