# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '分析テンプレート',
                'verbose_name_plural': '分析テンプレート',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='指標名')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
                ('metric_type', models.CharField(choices=[('percentage', 'パーセント(%)'), ('ratio', '倍率'), ('amount', '金額(億円)'), ('number', '数値'), ('rate', '率')], default='number', max_length=20, verbose_name='指標タイプ')),
                ('metric_group', models.CharField(choices=[('profitability', '収益性'), ('growth', '成長性'), ('valuation', 'バリュエーション'), ('dividend', '配当'), ('financial_health', '財務健全性'), ('efficiency', '効率性'), ('scale', '規模・実績')], default='profitability', max_length=30, verbose_name='指標グループ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='単位')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最小値')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='最大値')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('chart_suitable', models.BooleanField(default=True, verbose_name='チャート表示に適している')),
            ],
            options={
                'verbose_name': '指標定義',
                'verbose_name_plural': '指標定義',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='値')),
                ('fiscal_year', models.CharField(blank=True, max_length=10, verbose_name='会計年度')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_metrics', to='company_master.companymaster', verbose_name='企業')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_metrics', to='analysis_template.metricdefinition', verbose_name='指標定義')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analysis_template.analysistemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'テンプレート指標',
                'verbose_name_plural': 'テンプレート指標',
                'ordering': ['company', 'metric_definition__display_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_master.companymaster', verbose_name='企業')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_template.analysistemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'テンプレート企業',
                'verbose_name_plural': 'テンプレート企業',
                'ordering': ['display_order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustryBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_code', models.CharField(max_length=10, verbose_name='業種コード')),
                ('industry_name', models.CharField(max_length=100, verbose_name='業種名')),
                ('average_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='業種平均値')),
                ('median_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='業種中央値')),
                ('lower_quartile', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='下位25%値')),
                ('upper_quartile', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='上位25%値')),
                ('excellent_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='優良基準値')),
                ('poor_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='要注意基準値')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('fiscal_year', models.CharField(max_length=10, verbose_name='会計年度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_benchmarks', to='analysis_template.metricdefinition', verbose_name='指標定義')),
            ],
            options={
                'verbose_name': '業種別ベンチマーク',
                'verbose_name_plural': '業種別ベンチマーク',
                'ordering': ['industry_code', 'metric_definition__display_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='総合スコア')),
                ('profitability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='収益性スコア')),
                ('growth_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成長性スコア')),
                ('valuation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='バリュエーションスコア')),
                ('financial_health_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='財務健全性スコア')),
                ('data_completeness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='データ完全性')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='順位')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='計算日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_scores', to='company_master.companymaster', verbose_name='企業')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_scores', to='analysis_template.analysistemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '企業スコア',
                'verbose_name_plural': '企業スコア',
                'ordering': ['-total_score'],
            },
        ),
        migrations.AddField(
            model_name='analysistemplate',
            name='companies',
            field=models.ManyToManyField(related_name='analysis_templates', through='analysis_template.TemplateCompany', to='company_master.companymaster', verbose_name='対象企業'),
        ),
    ]
