# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_templates', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddIndex(
            model_name='templatemetrics',
            index=models.Index(fields=['template', 'company'], name='analysis_te_templat_42e4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='templatemetrics',
            index=models.Index(fields=['metric_definition'], name='analysis_te_metric__9c406a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatemetrics',
            unique_together={('template', 'company', 'metric_definition', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='templatecompany',
            unique_together={('template', 'company')},
        ),
        migrations.AddIndex(
            model_name='industrybenchmark',
            index=models.Index(fields=['industry_code', 'metric_definition'], name='analysis_te_industr_f433ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='industrybenchmark',
            unique_together={('industry_code', 'metric_definition', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='companyscore',
            index=models.Index(fields=['template', '-total_score'], name='analysis_te_templat_dad3ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyscore',
            unique_together={('template', 'company')},
        ),
        migrations.AddIndex(
            model_name='analysistemplate',
            index=models.Index(fields=['user', '-updated_at'], name='analysis_te_user_id_f9c666_idx'),
        ),
    ]
