# Generated by Django 4.2.27 on 2026-03-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margin_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='margindata',
            new_name='margin_trac_stock_c_d6f83f_idx',
            old_name='margin_trac_stock_c_idx',
        ),
        migrations.RenameIndex(
            model_name='margindata',
            new_name='margin_trac_record__fc97a6_idx',
            old_name='margin_trac_record__idx',
        ),
    ]
