# Generated by Django 4.2.27 on 2026-03-17 13:21

import company_master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True, validators=[company_master.models.validate_date_format], verbose_name='日付')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='証券コード')),
                ('name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('market', models.CharField(blank=True, max_length=50, verbose_name='市場・商品区分')),
                ('industry_code_33', models.CharField(blank=True, max_length=10, verbose_name='33業種コード')),
                ('industry_name_33', models.CharField(blank=True, max_length=100, verbose_name='33業種区分')),
                ('industry_code_17', models.CharField(blank=True, max_length=10, verbose_name='17業種コード')),
                ('industry_name_17', models.CharField(blank=True, max_length=100, verbose_name='17業種区分')),
                ('scale_code', models.CharField(blank=True, max_length=10, verbose_name='規模コード')),
                ('scale_name', models.CharField(blank=True, max_length=50, verbose_name='規模区分')),
                ('unit', models.IntegerField(default=100, verbose_name='売買単位')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '企業マスタ',
                'verbose_name_plural': '企業マスタ',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='company_mas_code_59673d_idx'), models.Index(fields=['name'], name='company_mas_name_1e1bcf_idx'), models.Index(fields=['industry_code_33'], name='company_mas_industr_b48f54_idx')],
            },
        ),
    ]
