# Generated by Django 4.2.13 on 2025-06-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportview',
            options={},
        ),
        migrations.AlterField(
            model_name='reportview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス'),
        ),
    ]
