# Generated by Django 4.2.27 on 2026-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名')),
                ('position', models.CharField(choices=[('header', 'ヘッダー'), ('sidebar', 'サイドバー'), ('content_top', 'コンテンツ上部'), ('content_bottom', 'コンテンツ下部'), ('footer', 'フッター')], max_length=50, verbose_name='配置位置')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '広告配置',
                'verbose_name_plural': '広告配置',
            },
        ),
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ユニット名')),
                ('ad_client', models.CharField(help_text='例: ca-pub-3954701883136363', max_length=100, verbose_name='ad-client ID')),
                ('ad_slot', models.CharField(max_length=100, verbose_name='ad-slot ID')),
                ('template_type', models.CharField(blank=True, help_text='特定のテンプレート用（例：diary_tab、diary_list）', max_length=50, verbose_name='テンプレートタイプ')),
                ('ad_layout', models.CharField(blank=True, help_text='data-ad-layout値（例：in-article）', max_length=100, verbose_name='広告レイアウト')),
                ('ad_layout_key', models.CharField(blank=True, help_text='data-ad-layout-key値（例：-h2+d+5c-9-3e）', max_length=100, verbose_name='広告レイアウトキー')),
                ('custom_style', models.TextField(blank=True, help_text='カスタムCSSスタイル（例：display:block; text-align:center;）', verbose_name='カスタムスタイル')),
                ('custom_js', models.TextField(blank=True, help_text='追加のJavaScriptコード', verbose_name='カスタムJS')),
                ('is_fluid', models.BooleanField(default=False, help_text='Fluid型広告の場合はチェック', verbose_name='Fluid広告')),
                ('ad_format', models.CharField(choices=[('auto', '自動'), ('horizontal', '水平バナー'), ('vertical', '垂直バナー'), ('rectangle', 'レクタングル'), ('responsive', 'レスポンシブ'), ('fluid', '流体')], default='auto', max_length=20, verbose_name='広告フォーマット')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='幅')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高さ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '広告ユニット',
                'verbose_name_plural': '広告ユニット',
            },
        ),
        migrations.CreateModel(
            name='UserAdPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_ads', models.BooleanField(default=True, verbose_name='広告を表示する')),
                ('is_premium', models.BooleanField(default=False, help_text='プレミアムユーザーは広告が表示されません', verbose_name='プレミアムユーザー')),
                ('allow_personalized_ads', models.BooleanField(default=True, verbose_name='パーソナライズ広告を許可')),
            ],
            options={
                'verbose_name': 'ユーザー広告設定',
                'verbose_name_plural': 'ユーザー広告設定',
            },
        ),
    ]
