# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=200, verbose_name='件名')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('spam_score', models.IntegerField(default=0, verbose_name='スパムスコア')),
                ('is_spam', models.BooleanField(default=False, verbose_name='スパム判定')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='認証トークン')),
                ('is_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='認証日時')),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='認証期限')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
