# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earnings_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_master', '0001_initial'),
        ('stockdiary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdnetreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tdnet_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成者'),
        ),
        migrations.AddField(
            model_name='tdnetreport',
            name='related_stock_diaries',
            field=models.ManyToManyField(blank=True, related_name='related_tdnet_reports', to='stockdiary.stockdiary', verbose_name='関連投資記録'),
        ),
        migrations.AddField(
            model_name='tdnetpdfjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_jobs', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='tdnetpdfjob',
            name='disclosure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_jobs', to='earnings_analysis.tdnetdisclosure', verbose_name='開示情報'),
        ),
        migrations.AddField(
            model_name='tdnetpdfjob',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_jobs', to='earnings_analysis.tdnetreport', verbose_name='レポート'),
        ),
        migrations.AddField(
            model_name='tdnetdisclosure',
            name='company_master',
            field=models.ForeignKey(blank=True, help_text='company_masterテーブルへの参照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tdnet_disclosures', to='company_master.companymaster', verbose_name='企業マスタ'),
        ),
        migrations.AddField(
            model_name='sentimentanalysissession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類'),
        ),
        migrations.AddField(
            model_name='sentimentanalysishistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類'),
        ),
        migrations.AddIndex(
            model_name='financialbenchmark',
            index=models.Index(fields=['industry_category'], name='earnings_an_industr_1e85ed_idx'),
        ),
        migrations.AddIndex(
            model_name='financialbenchmark',
            index=models.Index(fields=['industry_category', 'industry_subcategory'], name='earnings_an_industr_d9cb67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialbenchmark',
            unique_together={('industry_category', 'industry_subcategory', 'reference_period')},
        ),
        migrations.AddField(
            model_name='financialanalysissession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類'),
        ),
        migrations.AddField(
            model_name='financialanalysishistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['securities_code', 'file_date'], name='earnings_an_securit_88a16f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['doc_type_code', 'legal_status'], name='earnings_an_doc_typ_447fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['company_name', 'submit_date_time'], name='earnings_an_company_a38b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['edinet_code', '-submit_date_time'], name='earnings_an_edinet__b2f7dc_idx'),
        ),
        migrations.AddField(
            model_name='companyfinancialdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.company', verbose_name='企業'),
        ),
        migrations.AddField(
            model_name='companyfinancialdata',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='出典書類'),
        ),
        migrations.AddIndex(
            model_name='tdnetreportsection',
            index=models.Index(fields=['report', 'order'], name='idx_tdnet_sec_rep_order'),
        ),
        migrations.AlterUniqueTogether(
            name='tdnetreportsection',
            unique_together={('report', 'order')},
        ),
        migrations.AddIndex(
            model_name='tdnetreport',
            index=models.Index(fields=['status', '-published_at'], name='idx_tdnet_rep_status_pub'),
        ),
        migrations.AddIndex(
            model_name='tdnetreport',
            index=models.Index(fields=['report_type', '-published_at'], name='idx_tdnet_rep_type_pub'),
        ),
        migrations.AddIndex(
            model_name='tdnetreport',
            index=models.Index(fields=['disclosure', '-created_at'], name='idx_tdnet_rep_disc_date'),
        ),
        migrations.AddIndex(
            model_name='tdnetdisclosure',
            index=models.Index(fields=['company_code', '-disclosure_date'], name='idx_tdnet_disc_co_date'),
        ),
        migrations.AddIndex(
            model_name='tdnetdisclosure',
            index=models.Index(fields=['disclosure_type', '-disclosure_date'], name='idx_tdnet_disc_type_date'),
        ),
        migrations.AddIndex(
            model_name='tdnetdisclosure',
            index=models.Index(fields=['is_processed', 'report_generated'], name='idx_tdnet_disc_status'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysissession',
            index=models.Index(fields=['session_id'], name='earnings_an_session_4d87ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysissession',
            index=models.Index(fields=['expires_at'], name='earnings_an_expires_be35ac_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysissession',
            index=models.Index(fields=['processing_status'], name='earnings_an_process_6b84d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysishistory',
            index=models.Index(fields=['document', 'analysis_date'], name='earnings_an_documen_ca725f_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysishistory',
            index=models.Index(fields=['sentiment_label'], name='earnings_an_sentime_332375_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysishistory',
            index=models.Index(fields=['analysis_date'], name='earnings_an_analysi_9a4ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysissession',
            index=models.Index(fields=['session_id'], name='earnings_an_session_589f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysissession',
            index=models.Index(fields=['expires_at'], name='earnings_an_expires_4adbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysissession',
            index=models.Index(fields=['processing_status'], name='earnings_an_process_c52cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysissession',
            index=models.Index(fields=['document', 'created_at'], name='earnings_an_documen_98b529_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysishistory',
            index=models.Index(fields=['document', 'analysis_date'], name='earnings_an_documen_983e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysishistory',
            index=models.Index(fields=['risk_level'], name='earnings_an_risk_le_6f0ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysishistory',
            index=models.Index(fields=['analysis_date'], name='earnings_an_analysi_16b656_idx'),
        ),
        migrations.AddIndex(
            model_name='financialanalysishistory',
            index=models.Index(fields=['cashflow_pattern'], name='earnings_an_cashflo_dc083e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialdata',
            index=models.Index(fields=['company', 'period_end'], name='earnings_an_company_7309d2_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialdata',
            index=models.Index(fields=['period_type', 'fiscal_year'], name='earnings_an_period__24e21b_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfinancialdata',
            index=models.Index(fields=['document'], name='earnings_an_documen_c8e0a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfinancialdata',
            unique_together={('document', 'period_type', 'period_start', 'period_end')},
        ),
    ]
