# Generated by Django 4.2.13 on 2025-07-05 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='セッションID')),
                ('overall_score', models.FloatField(blank=True, help_text='-1.0〜+1.0', null=True, verbose_name='全体感情スコア')),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'ポジティブ'), ('negative', 'ネガティブ'), ('neutral', '中立')], max_length=20, null=True, verbose_name='感情ラベル')),
                ('processing_status', models.CharField(choices=[('PENDING', '待機中'), ('PROCESSING', '処理中'), ('COMPLETED', '完了'), ('FAILED', '失敗')], default='PENDING', max_length=20, verbose_name='処理ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='分析結果詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類')),
            ],
            options={
                'verbose_name': '感情分析セッション',
                'verbose_name_plural': '感情分析セッション一覧',
                'db_table': 'earnings_analysis_sentiment_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='earnings_an_session_4d87ec_idx'), models.Index(fields=['expires_at'], name='earnings_an_expires_be35ac_idx'), models.Index(fields=['processing_status'], name='earnings_an_process_6b84d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(help_text='-1.0〜+1.0', verbose_name='全体感情スコア')),
                ('sentiment_label', models.CharField(choices=[('positive', 'ポジティブ'), ('negative', 'ネガティブ'), ('neutral', '中立')], max_length=20, verbose_name='感情ラベル')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='分析実行日時')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='実行ユーザーIP')),
                ('analysis_duration', models.FloatField(blank=True, null=True, verbose_name='分析処理時間（秒）')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earnings_analysis.documentmetadata', verbose_name='対象書類')),
            ],
            options={
                'verbose_name': '感情分析履歴',
                'verbose_name_plural': '感情分析履歴一覧',
                'db_table': 'earnings_analysis_sentiment_history',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['document', 'analysis_date'], name='earnings_an_documen_ca725f_idx'), models.Index(fields=['sentiment_label'], name='earnings_an_sentime_332375_idx'), models.Index(fields=['analysis_date'], name='earnings_an_analysi_9a4ab3_idx')],
            },
        ),
    ]
