# Generated by Django 5.2.3 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings_analysis", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisclosureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "securities_code",
                    models.CharField(
                        db_index=True, max_length=5, verbose_name="証券コード"
                    ),
                ),
                ("doc_id", models.CharField(max_length=8, verbose_name="書類管理番号")),
                ("file_date", models.DateField(verbose_name="ファイル日付")),
                (
                    "doc_type_code",
                    models.CharField(max_length=10, verbose_name="書類種別コード"),
                ),
                (
                    "doc_type_name",
                    models.CharField(max_length=100, verbose_name="書類種別表示名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "開示イベント",
                "verbose_name_plural": "開示イベント一覧",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("securities_code", "doc_id"),
                        name="uniq_disclosure_event_code_doc",
                    )
                ],
            },
        ),
    ]
