# Generated by Django 4.2.27 on 2026-03-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnings_analysis', '0003_add_forecast_reliability_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='earningsforecast',
            name='unique_forecast_per_period',
        ),
        migrations.AlterUniqueTogether(
            name='earningsforecast',
            unique_together={('company_code', 'fiscal_year', 'period_type')},
        ),
    ]
