# Generated by Django 5.2.3 on 2026-06-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings_analysis", "0003_disclosureevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningsSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "securities_code",
                    models.CharField(
                        db_index=True,
                        help_text="証券コード（4桁または末尾0付き5桁）",
                        max_length=5,
                        verbose_name="証券コード",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, verbose_name="企業名"),
                ),
                (
                    "earnings_date",
                    models.DateField(db_index=True, verbose_name="決算予定日"),
                ),
                (
                    "earnings_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="決算種別"
                    ),
                ),
                (
                    "market_segment",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="市場区分"
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提供元更新日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "決算予定",
                "verbose_name_plural": "決算予定",
                "ordering": ["earnings_date", "securities_code"],
                "indexes": [
                    models.Index(
                        fields=["earnings_date", "securities_code"],
                        name="earnings_an_earning_341399_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("securities_code", "earnings_date"),
                        name="uniq_earnings_code_date",
                    )
                ],
            },
        ),
    ]
