# Generated by Django 5.2.3 on 2026-07-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0006_master_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastertag",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="docs/analysis_templates/tag_master.md の細分タグ（インデント）に対応。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tags.mastertag",
                verbose_name="親タグ",
            ),
        ),
    ]
