# Generated by Django 4.2.27 on 2026-03-17 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pattern', models.CharField(max_length=255, unique=True, verbose_name='メールパターン')),
                ('block_type', models.CharField(choices=[('exact', '完全一致'), ('domain', 'ドメイン一致'), ('pattern', 'パターン一致')], default='exact', max_length=10, verbose_name='ブロックタイプ')),
                ('reason', models.CharField(choices=[('spam', 'スパム送信'), ('abuse', '不正利用'), ('fake', '偽装メール'), ('manual', '手動ブロック'), ('automated', '自動検出')], default='manual', max_length=20, verbose_name='ブロック理由')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
            ],
            options={
                'verbose_name': 'ブロック済みメール',
                'verbose_name_plural': 'ブロック済みメール',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IPアドレス')),
                ('cidr_notation', models.CharField(blank=True, help_text='例: 192.168.1.0/24', max_length=20, verbose_name='CIDR記法')),
                ('reason', models.CharField(choices=[('spam', 'スパム送信'), ('abuse', '不正利用'), ('security', 'セキュリティ脅威'), ('manual', '手動ブロック'), ('automated', '自動検出')], default='manual', max_length=20, verbose_name='ブロック理由')),
                ('description', models.TextField(blank=True, help_text='ブロックした理由の詳細説明', verbose_name='詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('expires_at', models.DateTimeField(blank=True, help_text='空の場合は無期限', null=True, verbose_name='有効期限')),
            ],
            options={
                'verbose_name': 'ブロック済みIP',
                'verbose_name_plural': 'ブロック済みIP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('ip', 'IPアドレス'), ('email', 'メールアドレス')], max_length=10, verbose_name='ブロックタイプ')),
                ('blocked_value', models.CharField(max_length=255, verbose_name='ブロックされた値')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='アクセス元IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='リクエストパス')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ブロック日時')),
            ],
            options={
                'verbose_name': 'ブロック履歴',
                'verbose_name_plural': 'ブロック履歴',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
