"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h=(#w%%7ejhe=u$vjre&d%6u(-7a$js2x4*v76iq4_m3+7onk#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['exnok.pythonanywhere.com', 'localhost', '127.0.0.1','https://6e30-2400-2411-a761-e100-1436-fd6a-cfec-b578.ngrok-free.app']
CSRF_TRUSTED_ORIGINS = ['https://exnok.pythonanywhere.com', 'http://exnok.pythonanywhere.com','https://6e30-2400-2411-a761-e100-1436-fd6a-cfec-b578.ngrok-free.app']


SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',  # 必須
    'widget_tweaks',
    'ckeditor',
    'ckeditor_uploader',  # 追加
    'tinymce',
    'users',  # ← これがあるか確認
    'checklist',
    'tags',
    'stockdiary',
    'analysis_template',
    # django-allauth関連
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Googleプロバイダー
]


# メディアファイルの設定
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CKEditor の設定
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'mobile_friendly': {
        'toolbar': 'Basic',
        'height': 300,
        'width': '100%',
        'toolbar_Basic': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink', 'Image'],
            ['Source'],
        ],
        'removePlugins': 'resize',
        'extraPlugins': 'autogrow',
        'autoGrow_minHeight': 200,
        'autoGrow_maxHeight': 600,
        'image2_alignClasses': ['image-left', 'image-center', 'image-right'],
        'image2_disableResizer': True,
    },

    'default': {
        'toolbar': 'Custom',
        'height': 300,
        'width': '100%',
        # iPhoneに最適化したツールバー
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Image'],
            ['Source'],
        ],
        'removePlugins': 'resize,elementspath',
        'extraPlugins': 'autogrow,uploadimage',
        'autoGrow_minHeight': 200,
        'autoGrow_maxHeight': 500,
        'image2_disableResizer': True,
        'forcePasteAsPlainText': True,
        # モバイル向け最適化
        'extraAllowedContent': 'img[width,height,align]',
        'disableNativeSpellChecker': False,
        'scayt_autoStartup': False,
        'disableObjectResizing': True,
        'disableNativeTableHandles': True,
        'removeDialogTabs': 'image:advanced;link:advanced',
        'contentsCss': ['/static/css/ckeditor-mobile.css'],
    },
}

TINYMCE_DEFAULT_CONFIG = {
    'theme': 'silver',
    'width': '100%',
    'height': 300,
    'menubar': False,
    'plugins': 'link image lists table code',
    'toolbar': 'bold italic | bullist numlist | link image table | code',
    'mobile': {
        'plugins': 'link image lists table',
        'toolbar': 'bold italic | bullist numlist | link image'
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # 追加
]

AUTHENTICATION_BACKENDS = [
    # デフォルトのDjango認証バックエンド
    'django.contrib.auth.backends.ModelBackend',
    
    # allauth固有の認証バックエンド
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Sitesフレームワークの設定
SITE_ID = 1
# allauth設定
ACCOUNT_EMAIL_VERIFICATION = 'none'  # メール検証を無効（必要に応じて 'mandatory' に変更）
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = True  # ユーザー情報を自動的に取得
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'DIRECT_REDIRECT_URI': True  # 中間ページをスキップ
    }
}

ROOT_URLCONF = 'config.urls'

SOCIALACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSocialSignupForm',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'stockdiary:home'
LOGOUT_REDIRECT_URL = 'users:login'
