# Generated by Django 4.2.20 on 2025-03-11 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockdiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='analysis_templates.analysistemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('field_type', models.CharField(choices=[('number', '数値'), ('percentage', 'パーセント値'), ('text', 'テキスト'), ('date', '日付'), ('boolean', '真偽値（はい/いいえ）'), ('rating', '評価（1-5）')], max_length=20)),
                ('unit', models.CharField(blank=True, help_text='数値の単位（円、倍など）', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('benchmark_value', models.FloatField(blank=True, help_text='業界平均値などの基準値', null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='analysis_templates.templategroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='analysis_templates.analysistemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='StockAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_data', to='stockdiary.stockdiary')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='analysis_templates.analysistemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('analysis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='analysis_templates.stockanalysisdata')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analysis_templates.templatefield')),
            ],
        ),
    ]
