# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', '作成'), ('updated', '更新'), ('downgraded', 'ダウングレード'), ('upgraded', 'アップグレード'), ('canceled', 'キャンセル'), ('payment_succeeded', '支払い成功'), ('payment_failed', '支払い失敗'), ('trial_started', 'トライアル開始'), ('trial_ended', 'トライアル終了')], max_length=20)),
                ('stripe_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('max_tags', models.IntegerField(default=5)),
                ('max_templates', models.IntegerField(default=3)),
                ('max_records', models.IntegerField(default=30)),
                ('show_ads', models.BooleanField(default=True)),
                ('export_enabled', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('price_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('price_yearly', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripeの価格ID', max_length=100, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='表示順序')),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
                ('scheduled_downgrade_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_downgrades', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'ユーザーサブスクリプション',
                'verbose_name_plural': 'ユーザーサブスクリプション',
            },
        ),
    ]
