# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='from_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_events', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='to_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_events', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_972750_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['stripe_event_id'], name='subscriptio_stripe__eca137_idx'),
        ),
        migrations.AddIndex(
            model_name='stripecustomer',
            index=models.Index(fields=['stripe_id'], name='subscriptio_stripe__738936_idx'),
        ),
    ]
