# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.db import migrations, models
import django.db.models.deletion
import stockdiary.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, max_length=3000, verbose_name='記録内容')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='記録時点の価格')),
                ('image', models.ImageField(blank=True, help_text='継続記録に関連する画像', null=True, upload_to=stockdiary.models.get_note_image_path)),
                ('note_type', models.CharField(choices=[('analysis', '分析更新'), ('news', 'ニュース'), ('earnings', '決算情報'), ('insight', '新たな気づき'), ('risk', 'リスク要因'), ('other', 'その他')], default='analysis', max_length=20)),
                ('importance', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10)),
                ('source_doc_id', models.CharField(blank=True, help_text='関連するEDINET書類のdoc_id', max_length=8, null=True, verbose_name='参照書類ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '継続記録',
                'verbose_name_plural': '継続記録',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DiaryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField(verbose_name='通知日時')),
                ('message', models.TextField(blank=True, max_length=200, verbose_name='メッセージ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日記通知設定',
                'verbose_name_plural': '日記通知設定',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '通知履歴',
                'verbose_name_plural': '通知履歴',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'プッシュ通知サブスクリプション',
                'verbose_name_plural': 'プッシュ通知サブスクリプション',
            },
        ),
        migrations.CreateModel(
            name='StockDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='銘柄コード')),
                ('stock_name', models.CharField(max_length=100, verbose_name='銘柄名')),
                ('reason', models.TextField(blank=True, max_length=5000, verbose_name='投資理由')),
                ('memo', models.TextField(blank=True, max_length=1000, verbose_name='メモ')),
                ('sector', models.CharField(blank=True, max_length=50, verbose_name='業種')),
                ('image', models.ImageField(blank=True, help_text='日記に関連する画像', null=True, upload_to=stockdiary.models.get_diary_image_path)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現在保有数')),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='平均取得単価')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='総取得原価')),
                ('realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='実現損益')),
                ('total_bought_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累計購入数')),
                ('total_sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累計売却数')),
                ('total_buy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累計購入額')),
                ('total_sell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累計売却額')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='取引回数')),
                ('cash_only_current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物保有数')),
                ('cash_only_average_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現物平均取得単価')),
                ('cash_only_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物総原価')),
                ('cash_only_realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物実現損益')),
                ('cash_only_total_bought_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計購入数')),
                ('cash_only_total_sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計売却数')),
                ('cash_only_total_buy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計購入額')),
                ('cash_only_total_sell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計売却額')),
                ('first_purchase_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='最初の購入日')),
                ('last_transaction_date', models.DateField(blank=True, null=True, verbose_name='最後の取引日')),
                ('latest_disclosure_date', models.DateField(blank=True, null=True, verbose_name='最新開示日')),
                ('latest_disclosure_doc_type_name', models.CharField(blank=True, max_length=50, verbose_name='最新開示種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_diaries', models.ManyToManyField(blank=True, related_name='linked_from', to='stockdiary.stockdiary', verbose_name='関連日記')),
            ],
            options={
                'verbose_name': '株式日記',
                'verbose_name_plural': '株式日記',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', '購入'), ('sell', '売却')], max_length=10, verbose_name='取引種別')),
                ('transaction_date', models.DateField(db_index=True, verbose_name='取引日')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='数量')),
                ('memo', models.TextField(blank=True, max_length=500, verbose_name='メモ')),
                ('is_margin', models.BooleanField(default=False, verbose_name='信用取引')),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='取引後保有数')),
                ('average_price_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='取引後平均単価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stockdiary.stockdiary')),
            ],
            options={
                'verbose_name': '取引',
                'verbose_name_plural': '取引',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_date', models.DateField(db_index=True, verbose_name='分割実行日')),
                ('split_ratio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='分割比率')),
                ('memo', models.TextField(blank=True, max_length=500, verbose_name='メモ')),
                ('is_applied', models.BooleanField(default=False, verbose_name='適用済み')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='適用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_splits', to='stockdiary.stockdiary')),
            ],
            options={
                'verbose_name': '株式分割',
                'verbose_name_plural': '株式分割',
                'ordering': ['-split_date'],
            },
        ),
    ]
