# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('stockdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdiary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
