# Generated by Django 4.2.20 on 2026-03-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', '-updated_at'], name='stockdiary__user_id_f731da_idx'),
        ),
    ]
