# Generated by Django 4.2.20 on 2026-03-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0002_stockdiary_stockdiary__user_id_f731da_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_average_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='現物平均取得単価'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_current_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物保有数'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_realized_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物実現損益'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_total_bought_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計購入数'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_total_buy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計購入額'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物総原価'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_total_sell_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計売却額'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='cash_only_total_sold_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='現物累計売却数'),
        ),
    ]
