# Generated by Django 4.2.27 on 2026-03-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockdiary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stockdiary.diarynotification'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diarynotification',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stockdiary.stockdiary'),
        ),
        migrations.AddField(
            model_name='diarynote',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='stockdiary.stockdiary'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['diary', 'transaction_date'], name='stockdiary__diary_i_50c4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksplit',
            index=models.Index(fields=['diary', 'split_date'], name='stockdiary__diary_i_36dc01_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', 'first_purchase_date'], name='stockdiary__user_id_169008_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', 'stock_symbol'], name='stockdiary__user_id_9783f6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', 'current_quantity'], name='stockdiary__user_id_a4b892_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', '-updated_at'], name='stockdiary__user_id_f731da_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='stockdiary__user_id_c0ab1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'is_read', '-sent_at'], name='stockdiary__user_id_e7f600_idx'),
        ),
        migrations.AddIndex(
            model_name='diarynotification',
            index=models.Index(fields=['diary', 'is_active'], name='stockdiary__diary_i_94e0b2_idx'),
        ),
    ]
