# Generated by Django 4.2.27 on 2026-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdiary", "0004_diarynote_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdiary",
            name="currency",
            field=models.CharField(
                choices=[("JPY", "円"), ("USD", "米ドル")],
                default="JPY",
                max_length=3,
                verbose_name="通貨",
            ),
        ),
    ]
