# Generated by Django 5.2.3 on 2026-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdiary", "0008_merge_0007_diarytagdirection_0007_rename_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarynote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("analysis", "分析更新"),
                    ("news", "ニュース"),
                    ("earnings", "決算情報"),
                    ("insight", "新たな気づき"),
                    ("risk", "リスク要因"),
                    ("retrospective", "振り返り"),
                    ("other", "その他"),
                ],
                default="analysis",
                max_length=20,
            ),
        ),
    ]
