# Generated by Django 5.2.3 on 2026-06-10 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earnings_analysis", "0003_disclosureevent"),
        ("stockdiary", "0009_alter_diarynote_note_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="disclosure_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="earnings_analysis.disclosureevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("disclosure_event__isnull", False)),
                fields=("user", "disclosure_event"),
                name="uniq_user_disclosure_event",
            ),
        ),
    ]
