# Generated by Django 5.2.3 on 2026-06-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0012_merge_0011_merge_memo_into_reason_0011_thesis_verdict'),
        ('stockdiary', '0013_alter_thesis_diary_fk'),
    ]

    operations = [
    ]
