# Generated by Django 5.2.3 on 2026-06-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0014_merge_20260618_2218'),
        ('stockdiary', '0014_merge_20260619_1128'),
    ]

    operations = [
    ]
