# Generated by Django 5.2.3 on 2026-06-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0015_merge_20260619_2253'),
        ('stockdiary', '0015_reasonversion_diarynote_content_5000'),
    ]

    operations = [
    ]
