# Generated by Django 5.2.3 on 2026-06-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0016_merge_20260619_2259'),
        ('stockdiary', '0016_thesis_basis_and_claim_500'),
    ]

    operations = [
    ]
