# Generated by Django 5.2.3 on 2026-06-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdiary', '0017_merge_20260620_0738'),
        ('stockdiary', '0017_remove_diarynote_importance'),
    ]

    operations = [
    ]
